// spectrum-metrics.js — the numbers behind a placement on the Investment Spectrum.
//
// Seven ratios per company, each one built from figures the company filed, shown as a
// ten / five / three-year average, as trailing twelve months, and as this year's estimate.
// Nothing here decides where a company belongs. It puts the evidence on the screen and
// leaves the placement to whoever is looking at it.
//
// History comes from js/spectrum-metrics-data.js (generated by
// scripts/spectrum/fetch-metrics.ps1 out of SEC XBRL). The forward column comes from the
// portal's own estimate datasets in js/results-data/, loaded on demand.

import { SPECTRUM_METRICS_DATA } from './spectrum-metrics-data.js';

const BY_TICKER = SPECTRUM_METRICS_DATA.reduce((m, c) => { m[c.ticker] = c; return m; }, {});

const pct = v => (v * 100).toFixed(1) + '%';
const pct0 = v => (v * 100).toFixed(0) + '%';
const mult = v => v.toFixed(2) + '×';

/* ─── The seven ─────────────────────────────────────────────────────────────
   `of(row, prev)` returns the ratio or null. A null is never a zero: it means
   the company does not file the line, and the cell stays blank rather than
   implying the metric is small.

   `polarity` only drives the direction of the bar in the UI; nothing here
   claims that a higher number is better.                                     */

export const METRICS = [
  {
    key: 'revGrowth', label: 'Revenue growth', short: 'Rev growth',
    hint: 'Year on year, as reported. Not adjusted for acquisitions or currency.',
    format: pct, kind: 'growth',
    of: (r, prev) => (prev && prev.revenue && r.revenue != null ? r.revenue / prev.revenue - 1 : null)
  },
  {
    key: 'grossMargin', label: 'Gross margin', short: 'Gross',
    hint: 'Gross profit over revenue. Blank where the filer reports no cost-of-sales line — banks, brokers and Disney among them.',
    format: pct0, kind: 'margin',
    of: r => (r.grossProfit != null && r.revenue ? r.grossProfit / r.revenue : null)
  },
  {
    key: 'opMargin', label: 'Operating margin', short: 'Operating',
    hint: 'Operating income over revenue, as filed — GAAP or IFRS, not the company\'s adjusted version.',
    format: pct0, kind: 'margin',
    of: r => (r.operating != null && r.revenue ? r.operating / r.revenue : null)
  },
  {
    key: 'cfoMargin', label: 'CFO margin', short: 'CFO',
    hint: 'Cash from operations over revenue.',
    format: pct0, kind: 'margin',
    of: r => (r.cfo != null && r.revenue ? r.cfo / r.revenue : null)
  },
  {
    key: 'fcfMargin', label: 'FCF margin', short: 'FCF',
    hint: 'Cash from operations less capital expenditure, over revenue.',
    format: pct0, kind: 'margin',
    of: r => (r.cfo != null && r.capex != null && r.revenue ? (r.cfo - r.capex) / r.revenue : null)
  },
  {
    key: 'capexRev', label: 'Capex / revenue', short: 'Capex/rev',
    hint: 'What a dollar of revenue costs in new property and equipment.',
    format: pct, kind: 'intensity',
    of: r => (r.capex != null && r.revenue ? r.capex / r.revenue : null)
  },
  {
    key: 'capexDa', label: 'Capex / D&A', short: 'Capex/D&A',
    hint: 'Above 1× the asset base is growing; below 1× it is being harvested.',
    format: mult, kind: 'ratio',
    of: r => (r.capex != null && r.da ? r.capex / r.da : null)
  }
];

export const WINDOWS = [
  { key: '10y', label: '10 years', years: 10 },
  { key: '5y', label: '5 years', years: 5 },
  { key: '3y', label: '3 years', years: 3 }
];

/* ─── History ────────────────────────────────────────────────────────────── */

// One row per fiscal year, oldest first, with all seven ratios resolved. The
// revenue level rides along because a compound growth rate needs the endpoints,
// not the year-by-year rates.
export function seriesFor(ticker) {
  const c = BY_TICKER[ticker];
  if (!c) return null;
  return c.years.map((y, i) => {
    const prev = i > 0 ? c.years[i - 1] : null;
    const values = {};
    for (const m of METRICS) values[m.key] = m.of(y, prev);
    return { fy: y.fy, end: y.end, form: y.form, revenue: y.revenue, values };
  });
}

/* Compound annual growth over the window, which is what a multi-year revenue
   number should be: averaging ten yearly growth rates overweights whichever
   year happened to be small, and would say something no shareholder ever
   earned. Only revenue compounds, so only revenue gets one — the margins and
   capital ratios are levels, and their window figure stays a plain average.

   `years` growth needs `years + 1` observations; where the history is shorter
   the span shrinks and is reported, rather than being labelled as ten. */
export function cagrFor(ticker, years) {
  const series = seriesFor(ticker);
  if (!series) return null;
  const window = series.slice(-(years + 1)).filter(r => r.revenue > 0);
  if (window.length < 2) return null;
  const first = window[0], last = window[window.length - 1];
  const span = window.length - 1;
  return {
    value: Math.pow(last.revenue / first.revenue, 1 / span) - 1,
    span, from: first.fy, to: last.fy
  };
}

// The last closed fiscal year, on its own — the anchor between a multi-year
// average and anything forward-looking.
export function lfyFor(ticker) {
  const series = seriesFor(ticker);
  if (!series || !series.length) return null;
  const row = series[series.length - 1];
  return { fy: row.fy, end: row.end, form: row.form, values: row.values };
}

// A plain mean of the years available inside the window. Years the company did
// not file are skipped and counted, so the UI can say "7 of 10" rather than
// quietly averaging a shorter history against a longer one.
export function averageFor(ticker, years) {
  const series = seriesFor(ticker);
  if (!series) return null;
  const window = series.slice(-years);
  const out = {};
  for (const m of METRICS) {
    const vals = window.map(r => r.values[m.key]).filter(v => v != null && isFinite(v));
    // Growth can only ever exist for one year fewer than the window holds — the
    // oldest year has nothing to grow from — so it is not short a year when it
    // has n-1 of them.
    const expected = m.kind === 'growth' ? Math.max(1, window.length - 1) : window.length;
    out[m.key] = vals.length
      ? { value: vals.reduce((a, b) => a + b, 0) / vals.length, n: vals.length, of: expected }
      : { value: null, n: 0, of: expected };
  }
  return { values: out, from: window[0], to: window[window.length - 1], span: window.length };
}

// Trailing twelve months. Growth compares against the same twelve months a year
// earlier, which the puller computes; where it could not, growth stays blank
// rather than being measured against the last closed year.
export function ttmFor(ticker) {
  const c = BY_TICKER[ticker];
  if (!c || !c.ttm) return null;
  const t = c.ttm;
  const values = {};
  for (const m of METRICS) {
    values[m.key] = m.key === 'revGrowth'
      ? (t.priorRevenue ? t.revenue / t.priorRevenue - 1 : null)
      : m.of(t, null);
  }
  return { end: t.end, note: t.note, values };
}

export function meta(ticker) {
  const c = BY_TICKER[ticker];
  if (!c) return null;
  return { currency: c.currency, tags: c.tags, firstYear: c.years[0], lastYear: c.years[c.years.length - 1] };
}

/* ─── This year's estimate ──────────────────────────────────────────────────
   Read from the portal's own Results datasets rather than a second source, so
   the Spectrum and the Results tab can never quote different numbers for the
   same company. Coverage is what those datasets happen to carry: only the eight
   companies with a dataset appear at all, and each carries a different set of
   lines — Alphabet models all seven, Tiendas 3B two. Everything else is blank,
   and the panel says so.                                                      */

const FORWARD = {
  AMZN:  { mod: './results-data/amzn.js',  name: 'amznResults',  keys: { rev: 'rev', capex: 'capex' } },
  GOOGL: { mod: './results-data/googl.js', name: 'googlResults', keys: { rev: 'rev', gp: 'gp', op: 'opinc', cfo: 'cfo', capex: 'capex', da: 'da' } },
  META:  { mod: './results-data/meta.js',  name: 'metaResults',  keys: { rev: 'rev', op: 'opinc', capex: 'capex', fcf: 'fcf' } },
  UBER:  { mod: './results-data/uber.js',  name: 'uberResults',  keys: { rev: 'rev', op: 'opinc', fcf: 'fcf' } },
  LYFT:  { mod: './results-data/lyft.js',  name: 'lyftResults',  keys: { rev: 'rev', capex: 'capex', fcf: 'fcf' } },
  TBBB:  { mod: './results-data/tbbb.js',  name: 'tbbbResults',  keys: { rev: 'rev', gp: 'gp' } }
};

const _forwardCache = {};

/* An estimate series does not always measure the same thing the filings do.
   Alphabet's consensus revenue is net of traffic acquisition costs — about 84%
   of the reported line — so dividing a consensus cost by a consensus revenue
   would have shown a 70% gross margin against 60% in the accounts, and the
   estimate column would have been reporting a different company.

   So the estimate is used for the rate of change only, and applied to the last
   reported level: est = reported[t-1] × (series[t] / series[t-1]). Any constant
   difference in definition cancels, and the column lines up with the history
   beside it. Where there is no prior-year estimate to compare against, the raw
   figure is used and the offset, if any, comes with it. */
function pickSource(metric, index) {
  if (!metric) return null;
  if (metric.summit && metric.summit[index] != null) return 'summit';
  if (metric.cons && metric.cons[index] != null) return 'cons';
  return null;
}

// `anchorIdx` is the last period with a reported actual. Every forward year is
// anchored to that same one, so the second estimated year carries the whole
// cumulative change rather than compounding one anchoring error onto another.
function anchored(metric, index, source, anchorIdx) {
  if (!metric) return null;
  const series = metric[source] || (metric.summit && metric.summit[index] != null ? metric.summit : metric.cons);
  if (!series || series[index] == null) return null;

  const baseEst = series[anchorIdx];
  const baseAct = metric.act && metric.act[anchorIdx];
  if (baseEst != null && baseAct != null && baseEst !== 0) {
    return baseAct * (series[index] / baseEst);
  }
  return series[index];
}

export async function forwardFor(ticker) {
  if (ticker in _forwardCache) return _forwardCache[ticker];
  const spec = FORWARD[ticker];
  if (!spec) return (_forwardCache[ticker] = null);

  let view;
  try {
    const mod = await import(spec.mod);
    view = mod[spec.name] && mod[spec.name].views && mod[spec.name].views.y;
  } catch (e) {
    return (_forwardCache[ticker] = null);
  }
  if (!view || !view.metrics) return (_forwardCache[ticker] = null);

  const rev = view.metrics[spec.keys.rev];
  if (!rev || !rev.periods) return (_forwardCache[ticker] = null);

  // This year is the first period with no reported actual yet.
  let i = rev.act ? rev.act.findIndex(v => v == null) : -1;
  if (i < 1) return (_forwardCache[ticker] = null);

  const source = pickSource(rev, i);
  if (!source) return (_forwardCache[ticker] = null);
  const anchorIdx = i - 1;

  // One forward year, resolved against the last reported year and against the
  // revenue of the year before it for the growth line.
  const yearAt = (idx, prevRevenue) => {
    const get = (slot) => (spec.keys[slot] ? anchored(view.metrics[spec.keys[slot]], idx, source, anchorIdx) : null);
    const revNow = get('rev');
    if (revNow == null) return null;

    const gp = get('gp'), op = get('op'), cfo = get('cfo'),
          capex = get('capex'), da = get('da'), fcf = get('fcf');
    const ratio = (a, b) => (a != null && b ? a / b : null);

    return {
      period: rev.periods[idx],
      revenue: revNow,
      values: {
        revGrowth: prevRevenue ? revNow / prevRevenue - 1 : null,
        grossMargin: ratio(gp, revNow),
        opMargin: ratio(op, revNow),
        cfoMargin: ratio(cfo, revNow),
        // A modelled free-cash-flow line is used where one exists; otherwise it
        // is built the way the history builds it, from cash flow less capex.
        fcfMargin: fcf != null ? ratio(fcf, revNow)
          : (cfo != null && capex != null ? (cfo - capex) / revNow : null),
        capexRev: ratio(capex, revNow),
        capexDa: capex != null && da ? capex / da : null
      }
    };
  };

  const lastActual = rev.act && rev.act[anchorIdx] != null ? rev.act[anchorIdx] : null;
  const nfy = yearAt(i, lastActual);
  if (!nfy) return (_forwardCache[ticker] = null);
  const nfy1 = i + 1 < rev.periods.length ? yearAt(i + 1, nfy.revenue) : null;

  return (_forwardCache[ticker] = {
    source: source === 'summit' ? 'Summit model' : 'Street consensus',
    nfy, nfy1
  });
}

// Which companies can carry a forward column at all — so a table can draw the
// header without waiting for every import to resolve.
export const FORWARD_TICKERS = Object.keys(FORWARD);
